### ISSUE TITLE
Part segmentation data

### ISSUE THREAD

**Issue by cy69855522** [FENGGENYU/PartNet#3]
Thank you for such a wonderful project and would you mind to share the ShapeNet part segmentation dataset or data loader?

**Comment by FENGGENYU** [comment]
Sorry, we don't provide all experiment weights and data based on several reasons.

1. The ShapeNet part segmentation dataset is available on many places.
2. The dataloader and network for semantic segmentation can be easily modified from our current codes.
3. Better github page organization.
