### ISSUE TITLE
MAYBE YOUR DATASET IS NOT COMPLETE. 

### ISSUE THREAD

**Issue by lidan233** [FENGGENYU/PartNet#4]
Can you tell me the meaning of the field named 'cell_boxs_correspond_objSerialNumber' in your 'part mesh indices' directory of your dataset?  For example, if you choose the 'bed' category and the obj file named '10027.obj', you notice that there are 45 leaf nodes and 63 parts of this mesh. However, I don' know how to build the relationship between the 45 leaf and the 63 parts. You know the max index of the 'part mesh indices' is 71, which is more than 63. There, I can not find the information, which help me build the relationship between the 45 nodes and 63 parts. And I don't know the meaning of 'cell_boxs_correspond_objSerialNumber' field. Thank you!

**Comment by FENGGENYU** [comment]
This question is already resolved personally.
