### ISSUE TITLE
How to create my own dataset?

### ISSUE THREAD

**Issue by ThinhPham24** [FENGGENYU/PartNet#5]
That's perfect work. I want to create my dataset, please give me on how to create it.

**Comment by FENGGENYU** [comment]
There are several steps.

1. Get fine-grained segmented part meshes.
2. Use our software to generate part graph.
3. Manually label part relations in part graph in our software.
4. Output part graph and transfer it into binary hierarchy structure.

I didn't clean codes for this part, but if you need them please let me know.

**Comment by ThinhPham24** [comment]
Thank you for your reply. I think I need them. Can you provide me with them?

**Comment by FENGGENYU** [comment]
Here is the software we used to do labeling, detect symmetries and generate obb files.

https://drive.google.com/file/d/1uqV2oOA_4-UQrjK82qFvTCtnD3WT5Gbp/view?usp=sharing

This is a brief instruction doc:
https://docs.google.com/document/d/12r0OH_Je9H4LXeczUg_nLt1m5Z3JwTyNt4rNQs2kM9A/edit?usp=sharing

Here is code we used to transfer obbs to our sym.mat and ops.mat file for PartNet. Btw, this matlab code is old and I don't clean this code, so it could be buggy.

https://drive.google.com/file/d/1GzvDtg_34uTC25S3FdWg0hAoQTnvzo1n/view?usp=sharing
